### ISSUE TITLE
update Jenkinsfile to run all the test in jdk8 and jdk11 (matrix)?

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#195]

**Comment by adietish** [comment]
we need to run on both given that wildfly servers < 14 wont run on java11

**Comment by adietish** [comment]
@odockal isn't this what you achieved in #218? Can you please confirm?

**Comment by odockal** [comment]
@adietish Nope, but can be done.

**Comment by odockal** [comment]
@adietish So I can image this to be realized via maven profile where one named, let's say, wildfly-13, is called on the jdk-1.8 configuration and second, wildfly-14 (15?) is being called on jdk11, right? But I see a couple of problems in jenkins file, we should not have this (running itests at least, maybe tests either) as a part of build step. I would rather to see test stage as a standalone unit...

**Comment by odockal** [comment]
@adietish Could you please assign me on this? Thanks.

**Comment by adietish** [comment]
@adietish I agree on **not** running integration-tests when building, but I'd think that we should run the unit-tests?

**Comment by odockal** [comment]
@adietish I would run them all, just in another stage basically...

**Comment by odockal** [comment]
Something like this, roughly saying:
stage build:
mvn clean install -DskipTests
stage tests:
mvn clean verify -Pintegration-tests
junit publish results

**Comment by adietish** [comment]
@odockal why wouldn't you run the tests in a normal build? I would think that unit-tests should be run in a normal build since they tell you if something is broken runtime-wise?

**Comment by odockal** [comment]
I am updating that a bit, you are right with this, I would do it this way:
**stage build:**
mvn clean install -fae 
* fail at the end - which will let run all the unit test and fail at the end when there are any test failures - it is big red stack trace, so even locally user would see that it went wrong
* no itests will be run at this moment
* run on rhel/linux only?
**stage itests:**
mvn clean verify -Pintegration-tests -DskipTests=true
junit publish results
archive artifacts
* this will skip already run unit tests, but I do not mind running it again - it is fast)
* itests will be run on jdk 1.8/11 matrix.

I am proposing this flow as the issue is to run TEST with jdk 1.8/11. So I assumed that you do not want to run unit tests redundantly if you meant run all tests - itests+unit tests on with different jdks. We can run whole pipeline in different machine. No problem. Either we can run build+unit tests on linux (for now) and itests in matrix.

**Comment by odockal** [comment]
@adietish we can close the issue, right?

**Comment by adietish** [comment]
@odockal I think that we should run the tests on MacOS too: the filewatcher service (the one that is notifying the server on changes in the filesystem) works slightly different on MacOS and is less reliable than on Linux/Windows.

**Comment by adietish** [comment]
Other than those 2 questions I'd generally agree with you on the rest :)

**Comment by adietish** [comment]
@odockal can we please also post a link to the jenkins build here for the sake of documentation?

**Comment by adietish** [comment]
@odockal 
1. I would have unit and integration tests run on MacOS, too, agree? And sure, we can have this in a different issue.
2. ok

**Comment by adietish** [comment]
closing given that the remaining task, to run tests on MacOS, too, will be tackled in a different issue.

**Comment by odockal** [comment]
@adietish Thanks.
