### ISSUE TITLE
fix integration tests

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#217]
we moved integration tests to the *integration-tests* maven profile. We should now fix those tests.

**Comment by odockal** [comment]
In my opinion the problem was in this [line]. Itests classes uses mismatched data folder and so there was some trash configuration from previous unit tests run that was not cleared and server creation returned error status that server id already exists. (In short)

https://github.com/redhat-developer/rsp-server/blob/master/distribution/integration-tests/src/test/java/org/jboss/tools/rsp/itests/util/RSPServerHandler.java#L30

**Comment by odockal** [comment]
In my opinion the problem was in this [line]. Itests classes uses mismatched data folder and so there was some trash configuration from previous unit tests run that was not cleared and server creation returned error status that server id already exists. (In short)

[line]: https://github.com/redhat-developer/rsp-server/blob/master/distribution/integration-tests/src/test/java/org/jboss/tools/rsp/itests/util/RSPServerHandler.java#L30
