### ISSUE TITLE
Should generate request types that are bound to response types

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#252]
To have early compile-time warnings in rsp-client whenever the rsp-server API changes we should have request types that are bound to the response types. 
See https://github.com/redhat-developer/rsp-client/issues/74

**Comment by robstryker** [comment]
Fixed in https://github.com/redhat-developer/rsp-client/pull/79  and  generation work done in:

* 5f874f6 - Much discussion on client timeouts (8 days ago) <Rob Stryker>
* a51d508 - More changes to generation (8 days ago) <Rob Stryker>
* 81207e4 - Adding 'Async' to each method name is dumb (9 days ago) <Rob Stryker>
* 0308290 - Small cleanup for client generation (9 days ago) <Rob Stryker>
