### ISSUE TITLE
"Properties" should provide more details like home etc.

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#326]

**Comment by adietish** [comment]
Steps:
1. ASSERT: have a server 
1. EXEC: in the context menu pick "Properties"

Result:
```
Server Name: wlf16
Server Type Id: org.jboss.ide.eclipse.as.wildfly.160
Server Description: WildFly 16.x
```
Expected result:
Provide more detail like server home, java home, etc.

**Comment by robstryker** [comment]
Seems this was implemented in vscode-adapters with no additional APIs on the server, so the client doesn't have access to this stuff at the moment.   This would require some new API, in order to list all the existing attributes of a server, which could also theoretically be used to allow a client to update those various fields as well.

**Comment by robstryker** [comment]
I would argue this is now fixed via the edit-server action? All existing properties can be seen and edited, yes? 

It's also possible that the "properties" action in vscode is no longer needed since we have edit server? WDYT?  @adietish

**Comment by robstryker** [comment]
https://github.com/redhat-developer/vscode-rsp-ui/issues/39

Action has been removed. Instead user can edit server in an editor.
