### ISSUE TITLE
Should be able to provide JAVA_OPTS for a server

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#422]
We currently dont allow to provide JAVA_OPTS for a server. Users may want to provide larger memory settings for large projects.

[Marcel Körbler](https://github.com/Somebody25) told us on [Gitter](https://gitter.im/redhat-developer/server-connector):

> Hello! I was just trying to use this extension to deploy a larger project on Wilfly 10. Is there a possibility to set the JAVA_OPTS parameter because this project needs more RAM to work and I couldn't really find a way how to do this

> I already selected a server on the disk and also tried to set the standalone.conf.bat parameters (I'm on windows). This does work if I start the server manually with the standalone.sh in a terminal but the extension seems to ignore the settings there. If I start the server with the extension it dies because of to little RAM.

this is a blocker for https://github.com/redhat-developer/vscode-server-connector/issues/375

**Comment by adietish** [comment]
CC: @Somebody25

**Comment by adietish** [comment]
@robstryker dare to comment please?

**Comment by robstryker** [comment]
JAVA_OPTS is a flag in the shell script which is used to generate the command line. JAVA_OPTS is not actually a system property or environment variable used by the running server process itself. 

We currently don't run wildfly through the shell script, so standalone.sh / .bat  and standalone.conf are not used. They are completely ignored because we run directly to the java jar command through a jar entry point. 

We do have APIs to possibly override "launch attributes" (See RSPServer.getRequiredLaunchAttributes() / RSPServer.getOptionalLaunchAttributes) but these are currently not implemented in any server adapter because their workflow was never really seriously worked out. 

The debate is whether to treat the launch as something unique and separate that the user can edit directly, with its own backing file / UI / etc,  or whether to try to merge these in with server attributes that can currently be edited directly when editing a server. 

We will discuss with team how best to implement this and allow this functionality to be taken advantage of by users.

**Comment by adietish** [comment]
@robstryker +1, makes a lot of sense to me to allow larger mem et all

**Comment by robstryker** [comment]
See PR for more discussion
