### ISSUE TITLE
Moving to java 11 as we should adapt to newer Java system than 1.8

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server#631]
Think to move to java 11 as a version to compile against and run on. To be set as Java runtime env. 

* Probably we will need to set in poms:
```
<maven.compiler.source>11</maven.compiler.source>
<maven.compiler.target>11</maven.compiler.target>
```
* Also resolve removed java ee packages from jdk 11 (ie. javax.xml.bind).
* Move to module system

This is raw concept. Feel free to discuss.

**Comment by robstryker** [comment]
Is this still necessary if the build now works?

**Comment by odockal** [comment]
Well. once it will be. Why not to slowly transit there already?

**Comment by robstryker** [comment]
The build and release are now one way or another only functional on java 11 via the build matrix due to integration tests failing with recent wildfly 27 examples. We still compile down to java8 bytecode because our code does not use any java11 syntax ourselves and there's no real reason to change this until we want to do so or a library we want to use requires us to do so. I suspect there's nothing left to do here for now unless something blocks us forcing us to act.
